[uwsgi]
module = app:app

http = %(ENV_IP, 0.0.0.0):%(ENV_PORT, 8000)

manage-script-name = true
thunder-lock = true
cache2 = name=light_mail,items=10,blocksize=262144 ; block-size= 256KB

master = true
processes = %(ENV_PROCESSES, 2)
threads = %(ENV_THREADS, 2)

die-on-term = true

vacuum = true
need-app = true
disable-logging = true
